"""Inject OGP / Twitter Card / canonical meta tags into all polaris-lp HTML pages.

Idempotent: re-runs skip already-injected files.
Use --force to rewrite, --dry-run to preview without writing.

Usage:
    python3 scripts/inject-meta-tags.py
    python3 scripts/inject-meta-tags.py --dry-run
    python3 scripts/inject-meta-tags.py --force
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://www.polaris-app.jp"
SITE_NAME = "Polaris"
LOCALE = "ja_JP"

# ディレクトリ別 og:image
IMAGE_BY_DIR = {
    "glossary": f"{BASE_URL}/images/ogp-glossary.png",
    "contents": f"{BASE_URL}/images/ogp-contents.png",
    "learning": f"{BASE_URL}/images/ogp-learning.png",
    # ルートは glossary 流用（Polaris凍結中・ルート個別共有は稀）
    "_root": f"{BASE_URL}/images/ogp-glossary.png",
}

# og:type=website のページ
WEBSITE_PATHS = {
    "index.html",
    "help.html",
    "privacy.html",
    "terms.html",
    "tokutei.html",
    "404.html",
    "glossary/index.html",
    "contents/index.html",
    "learning/index.html",
}

MARKER_BEGIN = "<!-- OGP / Twitter Card / canonical (auto-generated by scripts/inject-meta-tags.py) -->"
MARKER_END = "<!-- /OGP -->"

DESC_RE = re.compile(r'<meta\s+name="description"[^>]*?>', re.DOTALL | re.IGNORECASE)
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.DOTALL | re.IGNORECASE)
DESC_CONTENT_RE = re.compile(
    r'<meta\s+name="description"\s+content="([^"]*)"', re.IGNORECASE
)
EXISTING_BLOCK_RE = re.compile(
    re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END) + r"\n?",
    re.DOTALL,
)


def collect_pages() -> list[Path]:
    pages: list[Path] = []
    for p in sorted(ROOT.glob("*.html")):
        pages.append(p)
    for sub in ("glossary", "contents", "learning"):
        for p in sorted((ROOT / sub).glob("*.html")):
            pages.append(p)
    return pages


def relative_key(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def canonical_for(path: Path) -> str:
    rel = relative_key(path)
    if rel == "index.html":
        return f"{BASE_URL}/"
    if rel.endswith("/index.html"):
        return f"{BASE_URL}/{rel[: -len('index.html')]}"
    return f"{BASE_URL}/{rel}"


def og_type_for(rel: str) -> str:
    return "website" if rel in WEBSITE_PATHS else "article"


def og_image_for(rel: str) -> str:
    parts = rel.split("/", 1)
    if len(parts) == 2 and parts[0] in IMAGE_BY_DIR:
        return IMAGE_BY_DIR[parts[0]]
    return IMAGE_BY_DIR["_root"]


def extract_title(content: str) -> str | None:
    m = TITLE_RE.search(content)
    if not m:
        return None
    raw = m.group(1).strip()
    raw = re.sub(r"\s+", " ", raw)
    return html.unescape(raw)


def extract_description(content: str) -> str | None:
    m = DESC_CONTENT_RE.search(content)
    if not m:
        return None
    return html.unescape(m.group(1))


def build_block(title: str, description: str, canonical: str, og_type: str, og_image: str) -> str:
    esc_title = html.escape(title, quote=True)
    esc_desc = html.escape(description, quote=True)
    lines = [
        MARKER_BEGIN,
        f'<link rel="canonical" href="{canonical}">',
        f'<meta property="og:type" content="{og_type}">',
        f'<meta property="og:site_name" content="{SITE_NAME}">',
        f'<meta property="og:locale" content="{LOCALE}">',
        f'<meta property="og:title" content="{esc_title}">',
        f'<meta property="og:description" content="{esc_desc}">',
        f'<meta property="og:url" content="{canonical}">',
        f'<meta property="og:image" content="{og_image}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{esc_title}">',
        f'<meta name="twitter:description" content="{esc_desc}">',
        f'<meta name="twitter:image" content="{og_image}">',
        MARKER_END,
    ]
    return "\n    ".join(lines)


def process(path: Path, *, force: bool, dry_run: bool) -> str:
    rel = relative_key(path)
    content = path.read_text(encoding="utf-8")

    has_existing = MARKER_BEGIN in content

    if has_existing and not force:
        return f"SKIP existing: {rel}"

    title = extract_title(content)
    description = extract_description(content)
    if not title:
        return f"WARN no <title>: {rel}"
    if not description:
        return f"WARN no description: {rel}"

    canonical = canonical_for(path)
    og_type = og_type_for(rel)
    og_image = og_image_for(rel)
    block = build_block(title, description, canonical, og_type, og_image)

    if has_existing:
        new_content = EXISTING_BLOCK_RE.sub(block + "\n", content, count=1)
        if new_content == content:
            return f"WARN replace failed: {rel}"
    else:
        # description タグ直後に挿入
        m = DESC_RE.search(content)
        if not m:
            return f"WARN no description tag: {rel}"
        insert_at = m.end()
        new_content = (
            content[:insert_at]
            + "\n\n    "
            + block
            + content[insert_at:]
        )

    if dry_run:
        return f"DRY  would write: {rel} ({og_type}, {og_image.rsplit('/', 1)[-1]})"

    path.write_text(new_content, encoding="utf-8")
    return f"WROTE: {rel} ({og_type}, {og_image.rsplit('/', 1)[-1]})"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="show what would change without writing")
    parser.add_argument("--force", action="store_true", help="rewrite even if already injected")
    parser.add_argument("--filter", help="only process paths containing this substring")
    args = parser.parse_args()

    pages = collect_pages()
    if args.filter:
        pages = [p for p in pages if args.filter in relative_key(p)]

    counts = {"WROTE": 0, "SKIP": 0, "DRY": 0, "WARN": 0}
    for path in pages:
        msg = process(path, force=args.force, dry_run=args.dry_run)
        kind = msg.split(":", 1)[0].split()[0]
        counts[kind] = counts.get(kind, 0) + 1
        print(msg)

    print("---")
    print(f"Total: {len(pages)} pages | " + " ".join(f"{k}={v}" for k, v in counts.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
